### ISSUE TITLE
Project page item contents overflow on hover effect

### ISSUE THREAD

**Issue by Hyokune** [lincolnChoy/lincolnChoy#6]
The items seem to have the overflow property visible so when you hover over them, part of the content starts outside the box.
It would be nice if the overflow was hidden so the animation is clean.

![image](https://user-images.githubusercontent.com/19813076/85096322-1d77c780-b248-11ea-9186-c7fbb3327c47.png)

**Comment by lincolnChoy** [comment]
Great find, ty friend :)
